### ISSUE TITLE
Issue with reading scale factor of "SymphonyMilkyWay" suite

### ISSUE THREAD

**Issue by Xiaolong-Du** [phil-mansfield/symphony#9]
Reading the scale factor of "SymphonyMilkyWay" suite will raise the following error:

`ValueError: The halo in SymphonyMilkyWay/Halo023 does not belong to a recognized suite.` 

This error is caused by the following lines in the function `scale_factors` of `symlib/lib.py`:

    suite_name = halo_dir_to_suite_name(dir_name)
    if (suite_name in ["SymphonyLMC", "SymphonyGroup", "SymphonyMilkyWayDisk",
                       "SymphonyMilkyWayDiskDMO", "EDEN_MilkyWay_8K",
                       "EDEN_MilkyWay_16K"
                      "SymphonyMilkyWay", "MWest", "SymphonyMilkyWayLR",
                       "SymphonyMilkyWayHR"] or
        dir_name in ["SymphonyLMC", "SymphonyGroup", "SymphonyMilkyWayDisk",
                     "SymphonyMilkyWayDiskDMO", "EDEN_MilkyWay_8K",
                     "EDEN_MilkyWay_16K",
                     "SymphonyMilkyWay", "MWest", "SymphonyMilkyWayLR",
                     "SymphonyMilkyWayHR"]):

A comma is missing at he end of the fourth line.

**Comment by phil-mansfield** [comment]
Ah sorry that I missed this. I had covid. This should be fixed in the latest version.

**Comment by Xiaolong-Du** [comment]
Hi @phil-mansfield , thank you for looking into this.  I hope you have fully recovered now. I think the issue still exists in the latest version.

**Comment by phil-mansfield** [comment]
Oops, you're right. It was fixed on my local version, but I didn't push it. Can you check again (v1.4.17)?

**Comment by Xiaolong-Du** [comment]
> Oops, you're right. It was fixed on my local version, but I didn't push it. Can you check again (v1.4.17)?

Yes, I just tried. The issue is fixed in v1.4.17. Thanks again.

**Comment by phil-mansfield** [comment]
Excellent. I'll close the issue now. Sorry again for the long initial wait!
